name:               antiope-contract
version:            6.0.3
category:           Services
author:             Arbor Networks
maintainer:         mayhem@arbor.net
copyright:          Arbor Networks
license:            MIT
homepage:           https://github.com/packetloop/antiope-contract#readme

description:         Please see the README on Github at <https://github.com/arbor/antiope#readme>

extra-source-files:
- contract/file_change_message.avsc
- contract/resource_changed.avsc
- README.md

dependencies:
- base >=4.7 && <5
- aeson
- antiope-s3
- avro
- aeson
- bytestring
- text

library:
  source-dirs: src
  exposed-modules:
    - Antiope.Contract.SQS.FileChangeMessage
    - Antiope.Contract.SQS.ResourceChanged
  ghc-options: -Wall
  when:
  - condition: os(osx)
    cpp-options:
    - -D__attribute__(A)=
    - -D_Nullable=
    - -D_Nonnull=
