name:                antiope-s3
version:             2.0.0
github:              "arbor/antiope"
license:             MIT
category:            Services
author:              Tyler Durden
maintainer:          mayhem@arbor.net
copyright:           Arbor Networks

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/arbor/antiope#readme>

default-extensions:
- BangPatterns
- GeneralizedNewtypeDeriving
- OverloadedStrings
- TupleSections

dependencies:
- base >= 4.7 && < 5
- amazonka        >= 1.6
- amazonka-core   >= 1.6
- amazonka-s3     >= 1.6
- bytestring
- conduit
- conduit-extra
- exceptions
- http-types
- http-client
- lens
- monad-logger
- mmorph
- mtl
- network-uri
- resourcet
- text
- transformers

library:
  source-dirs: src

tests:
  antiope-s3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - antiope-s3
